### PR TITLE
Draft API for selection, compatibility layer for SelectionSupport

### PR DESCRIPTION
**Pull request by CheatEx**
With review notes from PR #237

### CODE REVIEW

**Comment by timzam** [comment]
Looks good to me. We could decide on the id type later.

**Comment by katepol** [comment]
OK with me, though I'd like to make SelectionSupport.setSelectionController() package local.
I can't see matching pull request to datapad for merge.

**Comment by CheatEx** [comment]
I'm not aware about the process of synchronous merge. I assumed the person
who merges this could fix the import in StatementCell.

On Thu, Apr 21, 2016 at 8:09 PM, Ekaterina Frolova <notifications@github.com

**Comment by timzam** [comment]
It's not only an import. You should have prepared a pull request in datapad as well.

C:\jetpad\JetBrains\datapad\components\input-output-editor\src\main\java\jetbrains\datapad\inputOutputEditor\mapper\toDom\modelInput\CollaboratorsSupportImpl.java
Error:(356, 55) java: SELECTION_SUPPORT is not public in jetbrains.jetpad.projectional.selection.SelectionSupport; cannot be accessed from outside package
Error:(357, 28) java: isLowerPrioritySelection() is not public in jetbrains.jetpad.projectional.selection.SelectionSupport; cannot be accessed from outside package

**Comment by CheatEx** [comment]
@timzam https://github.com/JetBrains/datapad/pull/17

**Pull request merged**
