### PR TITLE
initialisation bug in SelectionSupport/Controller

### PR DESCRIPTION
**Pull request by CheatEx**

### CODE REVIEW

**Comment by timzam** [comment]
Looks good to me.

**Comment by solomatov** [comment]
I don't see test here. @timzam please don't accept the pull request without tests.

**Comment by timzam** [comment]
@solomatov Ok. Sorry, I forgot about tests here.

**Comment by CheatEx** [comment]
I wasn't able to reproduce the issue in test setup quickly. Looks like it
appears only in async mappers. Should I spend more time on reproducing this
issue?

**Comment by katepol** [comment]
As we have agreed with @solomatov before, bugs specific for GWT mappers shouldn't be covered with tests.

**Comment by CheatEx** [comment]
To clear thing up: I don't think the issue is GWT-specific, but the test needs AsyncMapper/EventBus. They're located in another module, depend on JS event dispatch and have small amount of native JS code. It's refactorable, but I doubt the resulting test really worth the effort.

**Comment by solomatov** [comment]
Ok, let's proceed without tests.

**Pull request merged**
